django_cafe_example/urls.py
from django.contrib import admin
from django.urls import path, include
from main_app.views import main_view
from django.conf import settings
from django.conf.urls.static import static
from account.views import registration_view, login_view, logout_view

urlpatterns = [
    path('admin/', admin.site.urls),

    path('registation/', registration_view, name='registation'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('manager/', include('manager.urls')),
    path('', main_view)
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

manager/urls.py
from django.urls import path
from .views import reservation_list, update_reservation

app_name = 'manager'

urlpatterns = [
    path('reservations/', reservation_list, name='reservations'),
    path('reservations/update/<int:pk>/', update_reservation, name='update_reservation'),
]

manager/models.py
from django.db import models

# Create your models here.

manager/views.py
from django.shortcuts import render, redirect
from main_app.models import Reservation
from django.contrib.auth.decorators import login_required, user_passes_test


def is_manager(user):
    return user.groups.filter(name='manager').exists()


@login_required(login_url='/login/')
@user_passes_test(is_manager)
def reservation_list(request):
    messages = Reservation.objects.filter(is_processed=False)
    return render(request, 'reservation_list.html', context={'reservations': messages})


@login_required(login_url='/login/')
@user_passes_test(is_manager)
def update_reservation(request, pk):
    Reservation.objects.filter(pk=pk).update(is_processed=True)
    return redirect('manager:reservations')

manager/templates/reservation_list.html
{% extends 'index.html' %}
{% block main_content %}
<section id="reserves">
        <div class="container">
            <div class="col-md-10 col-md-offset-1">
                {% for item in reservations %}
                    <div class="row">
                        <div class="col-md-3">
                            <a href="{% url 'manager:update_reservation' pk=item.pk %}">
                                <button type="button" class="btn btn-primary">Закрити замовлення</button>
                            </a>
                        </div>
                        <div class="col-md-3">{{ item.name }}</div>
                        <div class="col-md-3">{{ item.phone }}</div>
                        <div class="col-md-3">{{ item.visit_datetime|date:'d-m-Y' }}</div>
                    </div>
                    <div class="row">
                        <div class="col-md-3"></div>
                        <div class="col-md-9"><p>{{ item.message }}</p></div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </section>
{% endblock %}